# Generated by Django 3.0.14 on 2021-06-02 00:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jnv_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('word_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
            ],
        ),
    ]
