# Generated by Django 3.0.14 on 2021-06-08 00:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jnv_api', '0002_wordlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlists',
            name='word_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
    ]
