# Generated by Django 3.0.14 on 2022-11-10 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_api', '0002_courses_surveyanswers_surveys'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveys',
            name='course_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='survey_api.Courses'),
            preserve_default=False,
        ),
    ]
