# Generated by Django 3.0.14 on 2022-11-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_api', '0003_surveys_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveys',
            old_name='course_id',
            new_name='course',
        ),
    ]
